---
conf_files: "files/conf/dev.conf"
main_host: "masuraksha.com"
http_host: "dev.masuraksha.com"
erp_host: "deverp.masuraksha.com"
crm_host: "devcrm.masuraksha.com"
pos_host: "devpos.masuraksha.com"
static_host: "devstatic.masuraksha.com"
http_conf: "masuraksha"
http_port: "80"
https_port: "443"
ssh_port: "22"
Repo: "github.com/evervent/Masurksha-FSP.git"
git_username: "deepakevervent"
git_key: "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"
